export const PANCHAYATS = [
  'Aazhivaikkal', 'Akkaraivattam', 'Ambalapattu Thenpathi', 'Ambalapattu Vadapathi', 
  'Ammankudi', 'Archuthipattu', 'Arumulai', 'Athanakkottai', 'Avitanalla Vijayapuram', 
  'Ayankudi', 'Chinnaponnapoor', 'Cholapuram', 'Duraiyur', 'Eachankottai', 
  'Enathukkanpatti', 'Kaduvettiveduthi', 'Kakkarai', 'Kakkaraikottai', 
  'Kaliyaran Viduthi', 'Kandithampattu', 'Kannanthankudi Keelaiyur', 
  'Kannanthankudi Melaiyur', 'Kannukudi Keelpathi', 'Kannukudi Melpathi', 
  'Karaimeendarkottai', 'Kariyaviduthi', 'Karukkadipatti', 'Kasanadu Puthur', 
  'Kattukuruchi', 'Kattur', 'Kavalippatti', 'Kavarappattu', 'Keelaulur', 'Keelavannipattu', 
  'Kilamangalam', 'Kollankarai', 'Kollankarai Vallunda Pattu', 'Kovilur', 
  'Kulamangalam', 'Kulichappattu', 'Kurunkulam', 'Kurunkulam Keelpathi', 
  'Kurunkulam Melpathi', 'Kurunkulam West', 'Madikai', 'Mandalakkottai', 
  'Marunkulam', 'Melaulur', 'Moorthiyambalpuram', 'Mullurpattikadu', 'Naduvur', 
  'Nanchikottai Vallundampattu', 'Narathevankudikadu', 'Nathampadi Patti', 
  'Neduvakottai', 'Neivasal Thenpathi', 'Nemmali Thippiyakkudi', 
  'Okkanadu Keelaiyur', 'Okkanadu Melaiyur', 'Orathanadu', 'Pachur', 'Palamputhur', 
  'Palangandar', 'Panchanathikottai', 'Panikkondanveduthi', 'Paruthikottai', 
  'Peikarumpankottai', 'Pinnaiyur', 'Ponnapoor Keelpathi', 'Ponnapoor Melpathi', 
  'Poovathur', 'Pottalangkudikadu', 'Poyyundarkottai', 'Poyyundarkudikadu', 
  'Pulavankadu', 'Puthur', 'Ragavampalpuram', 'Rajali Viduthi', 
  'Sankaranar Kudikadu', 'Sennampatti', 'Sethurayankudikadu', 'Sillathur', 
  'Sivaveduthi', 'Solakankarai', 'Solakankudikadu', 'Soorakkottai', 
  'Thalaiyamangalam', 'Thekkur', 'Thelungankudukadu', 'Thennamanadu', 
  'Therkukottai', 'Thirukkanurpatti', 'Thirumangalakkottai Melaiur', 
  'Thirumangalakottai Keelaiur', 'Thirunallur', 'Thiruvonam', 'Thontarampattu', 
  'Thoppuviduthi', 'Unjiyaviduthi', 'Uranthairayan Kudikadu', 'Vadakkukottai', 
  'Vadakkur North', 'Vadakkur South Sethi', 'Vadaseri', 'Valamirankottai', 
  'Vandaiyar Iruppu', 'Vellur', 'Vettikadu', 'Vilar'
];
